// AUTO-GENERATED by scripts/build-reviews.mjs from /reviews/*.txt. Do not edit by hand.
import type { Review } from "./reviews";

export const allReviews: Review[] = [
  {
    "author": "Roger Dacombe",
    "source": "Google",
    "rating": 5,
    "quote": "I have used Joe's service three times now, twice for trees that had come down in bad weather. He responded and dealt with the problem very quickly and efficiently. I cannot state his ability to undertake a job highly enough, or indeed his prices, which are very fair and reasonable. I found all of the crew very polite and nice people. The service provided was first class and I cannot recommend him highly enough to anyone. You cannot go wrong by asking him to undertake a job for you."
  },
  {
    "author": "Richard Bowen",
    "source": "Google",
    "rating": 5,
    "quote": "Quality work and the price matched the quote exactly. Easy to deal with, would highly recommend them."
  },
  {
    "author": "Olivia N. E.",
    "source": "Google",
    "rating": 5,
    "quote": "Reliable service at a very fair price. Would highly recommend Joe and his team, and would use them again. Many thanks for doing such a great job!"
  },
  {
    "author": "Chloe Hitchins",
    "source": "Google",
    "rating": 5,
    "quote": "Joe and his team did the work at a reasonable price. Friendly, very tidy, and got the job done quickly to an excellent standard. Would definitely recommend."
  },
  {
    "author": "Charlotte Godfrey",
    "source": "Google",
    "rating": 5,
    "quote": "Phoned for an enquiry and they came when agreed. Excellent price for complete tree and stump removal, brilliant service from start to finish. Thanks Joseph and the team."
  },
  {
    "author": "Ma Za",
    "source": "Facebook",
    "rating": 5,
    "quote": "Excellent job by little Joe and his team had 3 very large trees cut down and they worked late into the evening to get the job done very tidy and professional would highly recommended"
  },
  {
    "author": "Richard Thomas",
    "source": "Facebook",
    "rating": 5,
    "quote": "The guys worked very hard for a long time. Superb results. Very polite and left the place so clean I could not believe it! Truly an honest and trustworthy service. Joe is a really nice guy too!!! Thank you so much."
  },
  {
    "author": "Shelly Louise",
    "source": "Facebook",
    "rating": 5,
    "quote": "Seen a recommendation on Facebook last night for Little Joes Tree Service, contacted them for a quote to have a tree taken down in my front garden, he responded quickly, came round today as agree and all done! Excellent job and very pleased! Thank you."
  },
  {
    "author": "Kenneth Baker",
    "source": "Facebook",
    "rating": 5,
    "quote": "Little Joe Tree Service carried out both significant tree clearance in a professional manner. The team worked very hard and cleaned up after to high standard. They also removed and replaced the fence again to a high standard. I have no hesitation in recommending them."
  },
  {
    "author": "Becky Cowan",
    "source": "Facebook",
    "rating": 5,
    "quote": "Very responsive, reasonably priced, and kept me updated on the time he'd be round. Quick stump removal with treatment and was very friendly and professional! No faff at all. Thank you 😊"
  },
  {
    "author": "Barnett Shay",
    "source": "Facebook",
    "rating": 5,
    "quote": "Come round to cut a tree/remove a stump, very professional and friendly service would definitely use again 10/10 👊"
  },
  {
    "author": "Dave Dobrijevic",
    "source": "Facebook",
    "rating": 5,
    "quote": "Great service by little Joe's, they've completed two jobs for us now very effectively. recommend 🌲"
  },
  {
    "author": "Tony Shervill",
    "source": "Facebook",
    "rating": 5,
    "quote": "Tony & Marion had a large fir tree, cut down and removed by Joe and his team. Brilliant service quick safe and professional. Thanks Joe."
  },
  {
    "author": "Karl Hudson",
    "source": "Facebook",
    "rating": 5,
    "quote": "Get at my pal very good in wot he's does 💯 thanks for wot you done mate very good and very tidy work effort 8/10 very much happy with the work I've had done with them"
  },
  {
    "author": "Leah Davies",
    "source": "Facebook",
    "rating": 5,
    "quote": "highly recommend. tidy, friendly fast, reliable and reasonably priced. would definitely use again"
  },
  {
    "author": "Sam Harris",
    "source": "Facebook",
    "rating": 5,
    "quote": "great work! quick easy and affordable definitely recommend using little Joe's tree services"
  },
  {
    "author": "Kerrie Louise",
    "source": "Facebook",
    "rating": 5,
    "quote": "recommend an excellent work from his team today I would recommend him to anyone outstanding work really happy with it on. time services"
  },
  {
    "author": "Harry D Kendrick",
    "source": "Facebook",
    "rating": 5,
    "quote": "Had joe and his team here done a excellent job would definitely use him again.. too work lads"
  },
  {
    "author": "Dean Haddrell",
    "source": "Facebook",
    "rating": 5,
    "quote": "Absolutely brilliant service, joe came to me to quote on the Tuesday, by Thursday he had completed it. Fast, efficient, professional and courteous would definitely recommend."
  },
  {
    "author": "Owen Fletcher",
    "source": "Facebook",
    "rating": 5,
    "quote": "absolute brilliant service very well recommended absolute brilliant job thank you very much a little joe's tree service"
  },
  {
    "author": "Josh Budgen",
    "source": "Facebook",
    "rating": 5,
    "quote": "Very good quick service very polite done a very good job would recommend to anyone who needs tree cutting or trimming and very well priced. ⭐⭐⭐⭐⭐"
  },
  {
    "author": "Andy Brent",
    "source": "Facebook",
    "rating": 5,
    "quote": "Hi thanks very much for the tree and stump removal it was the best price out of 5 firms and to be fair I don't think I could of had a cleaner job done and so polite and friendly and the tools u had to use and not leave any mess was incredibly decent"
  },
  {
    "author": "Charlee Ennis-Frost",
    "source": "Facebook",
    "rating": 5,
    "quote": "brilliant service quick and efficient turnt up on time price was good would definitely recommend and use myself again"
  },
  {
    "author": "Lee Grant",
    "source": "Facebook",
    "rating": 5,
    "quote": "Best work I've had done in ages top worker an top work done class bloke gets the job spotless an always does for a good price highly recommend"
  },
  {
    "author": "Mark Male",
    "source": "Facebook",
    "rating": 5,
    "quote": "Very professional from start to finish, would highly recommend. Job was very well done and will have him back in the future"
  },
  {
    "author": "Hayley Swash",
    "source": "Facebook",
    "rating": 5,
    "quote": "Highly recommend this service very good work"
  },
  {
    "author": "Sean Terry",
    "source": "Facebook",
    "rating": 5,
    "quote": "very professional and friendly on time cleaned up leaving are garden looking lovely and ready to relax in. grate price compared to most quotes I had. would highly recommend."
  },
  {
    "author": "Adam Silver",
    "source": "Facebook",
    "rating": 5,
    "quote": "top quality workmanship @ a very competitive price 👍🏼 thank you Joseph"
  },
  {
    "author": "John",
    "source": "Bark",
    "rating": 5,
    "quote": "Quoted on the Tuesday, work completed on the Thursday. Very punctual, professional, polite and tidied up after job complete. Would highly recommend!"
  },
  {
    "author": "Krys Greenland",
    "source": "Bark",
    "rating": 5,
    "quote": "Great, quick service. Very professional"
  },
  {
    "author": "Krys Greenland",
    "source": "Bark",
    "rating": 5,
    "quote": "Great job cutting up a fallen ash tree. Quick response and very professional. Thank you!"
  },
  {
    "author": "Anthony Phinn",
    "source": "Bark",
    "rating": 5,
    "quote": "Excellent job. Polite and courteous. Did the job very well, at a good price and cleaned up afterwards."
  },
  {
    "author": "Kate Adams",
    "source": "Bark",
    "rating": 5,
    "quote": "I was very impressed with the speed in which Joe contacted me regarding a quote and even more so at how quickly he was able to fit in the work. The team were very efficient at removing a sizeable bamboo and were even able to fit in an additional task whilst on site. I will definitely use this company again and am very grateful for their hard work. Would highly recommend them."
  },
  {
    "author": "Tim Morris",
    "source": "Bark",
    "rating": 5,
    "quote": "Fantastic service, quick efficient and very polite hard workers, cleaned up well after the work!"
  },
  {
    "author": "Joanne Sloan",
    "source": "Bark",
    "rating": 5,
    "quote": "Professional & courteous service, had tree stumps removed, highly recommended"
  },
  {
    "author": "Mr H Kattan",
    "source": "Bark",
    "rating": 5,
    "quote": "Excellent service. Joe and his brother could not have been anymore professional. They were on time, very polite and did a great job. I would not hesitate to recommend them."
  },
  {
    "author": "Jo",
    "source": "Bark",
    "rating": 5,
    "quote": "Excellent, friendly, polite and very well priced. Left areas tidy and kept up to date with progress. Very happy costumer would definately use again. Thankyou."
  },
  {
    "author": "Adrian Ahl",
    "source": "Bark",
    "rating": 5,
    "quote": "Excellent prompt service from a great team of people. Super tidy too"
  },
  {
    "author": "Lesley",
    "source": "Bark",
    "rating": 5,
    "quote": "Highly recommend. The team arrived on time and carried out the work required in shocking weather, rain and high winds. Very polite and tidy, will definitely use them again. Thank you."
  },
  {
    "author": "Mrs Yvonne Cook",
    "source": "Bark",
    "rating": 5,
    "quote": "Joe and his colleague were very friendly and efficient - gave me a quote and we agreed price and they did the job. No fuss. Excellent customer service!! Will use again."
  },
  {
    "author": "Charlee Frost",
    "source": "Bark",
    "rating": 5,
    "quote": "Really pleased Thankyou, left everything clean and tidy. Done the job I wanted great. Good price. Happy customer would recommend to family and friends. And will be needing you again soon. Thanks"
  },
  {
    "author": "Aaron Pennell",
    "source": "Bark",
    "rating": 5,
    "quote": "Little Joe's tree service did a great job on my trees and bushes I would recommend them to anyone they r nice and do a good job"
  },
  {
    "author": "Mark Wonnacott",
    "source": "Bark",
    "rating": 5,
    "quote": "They removed a hedge for me: very quick to respond, well done and a fair price."
  },
  {
    "author": "Juliette Macpherson",
    "source": "Bark",
    "rating": 5,
    "quote": "Joe came & quoted for the removal of two trees. He returned the following day at the time agreed & has done a fantastic job. Really impressed with the quality of work & how they tidied up afterwards."
  },
  {
    "author": "Cindy Harbut",
    "source": "Bark",
    "rating": 5,
    "quote": "Excellent. Very helpful. Talked me through what he would do. Very quickly and tidy"
  },
  {
    "author": "Debs",
    "source": "Bark",
    "rating": 5,
    "quote": "The Gentleman was the first person I actually texted after speaking to the others because he told me about his qualifications straight away and asked a lot more information about the job and was the cheapest."
  },
  {
    "author": "Simon Cheesman",
    "source": "Bark",
    "rating": 5,
    "quote": "They were quick to respond, polite and efficient. They cleaned up after and were very helpful."
  },
  {
    "author": "Karen Lawrence",
    "source": "Bark",
    "rating": 5,
    "quote": "Came out quickly after contacting us. Had to sort out access through house but they managed it. They done a great job and left everything tidy."
  },
  {
    "author": "Shirley Johnson",
    "source": "Bark",
    "rating": 5,
    "quote": "Very happy with the work they done and would recommend them. Saj"
  },
  {
    "author": "MR CLIVE J HARVEY",
    "source": "Bark",
    "rating": 5,
    "quote": "He did an excellent job and cleaned up after he had finished. I would thoroughly recommend him."
  },
  {
    "author": "Stuart Crighton",
    "source": "Bark",
    "rating": 5,
    "quote": "Very quick response to quote request. Arrived in the time window stated and did exactly as requested in a matter of minutes."
  },
  {
    "author": "nicola Doo",
    "source": "Bark",
    "rating": 5,
    "quote": "Polite, professional and super quick job with very big stump! Thanks Joe and Bobby… really pleased."
  },
  {
    "author": "Stephanie Murphy",
    "source": "Bark",
    "rating": 5,
    "quote": "I would highly recommend. They rang me immediately with a reasonable quote and in fact did my job 2 days later as they had a cancellation."
  },
  {
    "author": "neil or penny",
    "source": "Bark",
    "rating": 5,
    "quote": "Phoned immediately job posted with a quote. Some extra work done while he was here."
  },
  {
    "author": "Ruth Vasse",
    "source": "Bark",
    "rating": 5,
    "quote": "They were very responsive and courteous and completed the job quickly. I'm happy with the quality of the work."
  },
  {
    "author": "Mandy young",
    "source": "Bark",
    "rating": 5,
    "quote": "Excellent job, quick and tidy ………"
  },
  {
    "author": "Gareth Jarvis",
    "source": "Bark",
    "rating": 5,
    "quote": "I am more than pleased with their work. Did a good job and seem to be nice people. Good professional job done."
  },
  {
    "author": "Hannah",
    "source": "Bark",
    "rating": 5,
    "quote": "Quick response, great work at a great price"
  },
  {
    "author": "Sharon Ensor",
    "source": "Bark",
    "rating": 5,
    "quote": "Fast, polite. Tidy, not pushy. Sent photos of certificates."
  },
  {
    "author": "Ian Abrahams",
    "source": "Bark",
    "rating": 5,
    "quote": "Very quick response and same day service. Cheers"
  },
  {
    "author": "Trisha",
    "source": "Bark",
    "rating": 5,
    "quote": "I was contacted the same day! Quoted a price by photos. They arrived the same day and removed a large tree stump and a smaller tree stump! Efficient service, friendly guys. The job didn't go exactly to plan due to access issue with the machinery but they removed them both by hand. Happy with the outcome would use again."
  },
  {
    "author": "Kate yates",
    "source": "Bark",
    "rating": 5,
    "quote": "Great service. Would use again."
  },
  {
    "author": "Susan Lupton",
    "source": "Bark",
    "rating": 5,
    "quote": "Quick to respond. Carried out the work efficiently. Took off our gate without asking to gain access but did put it back properly."
  },
  {
    "author": "Robert Edes",
    "source": "Bark",
    "rating": 5,
    "quote": "What a great company no messing around, polite, efficient and tidy, will be definitely using again."
  },
  {
    "author": "Julian francis",
    "source": "Bark",
    "rating": 5,
    "quote": "Quick efficient and tidy. I would recommend"
  },
  {
    "author": "Richard Avery",
    "source": "Bark",
    "rating": 5,
    "quote": "Turned up on time and completed the job quickly and effectively at the agreed price."
  },
  {
    "author": "Mrs Sharon Evans",
    "source": "Bark",
    "rating": 5,
    "quote": "After a brief discussion a price was agreed and the job was carried out today. It is exactly as I wanted and nobody was here to supervise, there was no mess left behind and payment was made after I had seen the completed work. Very satisfied customer 👌"
  },
  {
    "author": "Richard Shuker",
    "source": "Bark",
    "rating": 5,
    "quote": "Extremely hard working, job well done"
  },
  {
    "author": "John Turner",
    "source": "Bark",
    "rating": 5,
    "quote": "Hard working guys very quick workers. Would recommend"
  },
  {
    "author": "Martin Williams",
    "source": "Bark",
    "rating": 5,
    "quote": "Highly courteous and efficient they undertook the root grinding of three stumps which they completed quickly and efficiently. I will certainly use them again."
  },
  {
    "author": "John Alkire",
    "source": "Bark",
    "rating": 5,
    "quote": "Once the confusion was resolved the job went well."
  },
  {
    "author": "Noelle Healy",
    "source": "Bark",
    "rating": 5,
    "quote": "Fantastic workers very polite it was a massive job but didn't stop until job was done cleared everything away left no mess reasonable prices hard working reliable so happy with my new hedges so thankyou"
  },
  {
    "author": "Natalie Smith",
    "source": "Bark",
    "rating": 5,
    "quote": "Professional and speedy, did a good job getting rid of our tree stump."
  },
  {
    "author": "Harry Murray",
    "source": "Bark",
    "rating": 5,
    "quote": "Very quick response, with excellent rates. Really happy with the job & service."
  },
  {
    "author": "David",
    "source": "Bark",
    "rating": 5,
    "quote": "Friendly service, good service and super fast. Would recommend."
  },
  {
    "author": "Peter Gurd",
    "source": "Bark",
    "rating": 5,
    "quote": "Really nice guy; prompt, polite, efficient and a great job done"
  },
  {
    "author": "Tommy",
    "source": "Bark",
    "rating": 5,
    "quote": "Quick, reliable and professional. Happy with the stump removal!"
  },
  {
    "author": "Mr Brian Upton",
    "source": "Bark",
    "rating": 5,
    "quote": "Little tree came gave us a price and got on with the job of cutting down the trunk of a tree. Very polite and tidied up afterwards. Would recommend them!"
  },
  {
    "author": "Steve Kempson",
    "source": "Bark",
    "rating": 5,
    "quote": "Polite friendly service, would recommend"
  },
  {
    "author": "Ella Henly",
    "source": "Bark",
    "rating": 5,
    "quote": "Reliable, tidy and reasonably priced. Joe and his team did a great job at removing our tree. Highly recommend."
  },
  {
    "author": "Sam",
    "source": "Bark",
    "rating": 5,
    "quote": "Great to work with! Great service! Great prices!"
  },
  {
    "author": "Aaron harris",
    "source": "Bark",
    "rating": 5,
    "quote": "We used Little Tree service for tree and branch removal in our garden. Would highly recommend. Joey and his team were professional, polite and left our garden spotless. Will definitely be using them in the future."
  },
  {
    "author": "T palmer",
    "source": "Bark",
    "rating": 5,
    "quote": "Great work and not as expensive as expected"
  },
  {
    "author": "A silver",
    "source": "Bark",
    "rating": 5,
    "quote": "A++ very professional. Polite and fast"
  },
  {
    "author": "Dan",
    "source": "Bark",
    "rating": 5,
    "quote": "Excellent fast and reliable service highly recommended a+++"
  },
  {
    "author": "Dean haddrell",
    "source": "Bark",
    "rating": 5,
    "quote": "Joseph and his gang turned up on time and took no time to get going when they arrived. The gang was very polite and hard working. I thought the job was reasonably priced and would definitely recommend to others and we will be having the gang back in the future."
  },
  {
    "author": "Richard mirams",
    "source": "Bark",
    "rating": 5,
    "quote": "Great job done on my property. Friendly and professional service. Thanks guys. Would highly recommend"
  },
  {
    "author": "Dean Collingwood",
    "source": "Bark",
    "rating": 5,
    "quote": "Joey and his team turned up to remove two trees they were extremely polite and done a brilliant job 5 stars would definitely use again"
  },
  {
    "author": "Adam Stubbs",
    "source": "Bark",
    "rating": 5,
    "quote": "Great service very polite and professional fast and very competitive pricing defiantly will use again in the future"
  }
];
