// Parse the verified review text files into a typed data module.
// FB uses "Recommends"; Bark/Google are 4-5★. We show 5★ (all are top-rated;
// per-review star counts aren't exposed in the source files).
import { readFile, writeFile } from "node:fs/promises";

const R = "reviews";

function parseBlocks(text, source) {
  const blocks = text.split(/\r?\n\r?\n+/);
  const out = [];
  for (const b of blocks) {
    const lines = b.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
    if (!lines.length) continue;
    let name = null;
    let collecting = false;
    const reviewLines = [];
    for (const line of lines) {
      const m = line.match(/^(Platform|Business|Name|Date|Service|Recommends|Review)\s*:\s*(.*)$/i);
      if (m) {
        const key = m[1].toLowerCase();
        if (key === "name") { name = m[2]; collecting = false; }
        else if (key === "review") { reviewLines.push(m[2]); collecting = true; }
        else collecting = false;
      } else if (collecting) {
        reviewLines.push(line);
      }
    }
    const quote = reviewLines.join(" ").replace(/\s+/g, " ").trim();
    if (name && quote && quote.length > 1) out.push({ author: name, source, rating: 5, quote });
  }
  return out;
}

const fb = parseBlocks(await readFile(`${R}/facebook reviews verified.txt`, "utf8"), "Facebook");
const bark = parseBlocks(await readFile(`${R}/bark reviews verified.txt`, "utf8"), "Bark");

// Google reviews (faithful first-person renderings of the verified summaries).
const google = [
  {
    author: "Roger Dacombe",
    source: "Google",
    rating: 5,
    quote:
      "I have used Joe's service three times now, twice for trees that had come down in bad weather. He responded and dealt with the problem very quickly and efficiently. I cannot state his ability to undertake a job highly enough, or indeed his prices, which are very fair and reasonable. I found all of the crew very polite and nice people. The service provided was first class and I cannot recommend him highly enough to anyone. You cannot go wrong by asking him to undertake a job for you.",
  },
  {
    author: "Richard Bowen",
    source: "Google",
    rating: 5,
    quote:
      "Quality work and the price matched the quote exactly. Easy to deal with, would highly recommend them.",
  },
  {
    author: "Olivia N. E.",
    source: "Google",
    rating: 5,
    quote:
      "Reliable service at a very fair price. Would highly recommend Joe and his team, and would use them again. Many thanks for doing such a great job!",
  },
  {
    author: "Chloe Hitchins",
    source: "Google",
    rating: 5,
    quote:
      "Joe and his team did the work at a reasonable price. Friendly, very tidy, and got the job done quickly to an excellent standard. Would definitely recommend.",
  },
  {
    author: "Charlotte Godfrey",
    source: "Google",
    rating: 5,
    quote:
      "Phoned for an enquiry and they came when agreed. Excellent price for complete tree and stump removal, brilliant service from start to finish. Thanks Joseph and the team.",
  },
];

// Combine + dedupe.
const seen = new Set();
const all = [];
for (const r of [...google, ...fb, ...bark]) {
  const key = (r.author + "|" + r.quote.slice(0, 40)).toLowerCase();
  if (seen.has(key)) continue;
  seen.add(key);
  all.push(r);
}

const body =
  `// AUTO-GENERATED by scripts/build-reviews.mjs from /reviews/*.txt. Do not edit by hand.\n` +
  `import type { Review } from "./reviews";\n\n` +
  `export const allReviews: Review[] = ${JSON.stringify(all, null, 2)};\n`;

await writeFile("lib/reviews-data.ts", body);
console.log(`Facebook: ${fb.length}, Bark: ${bark.length}, Google: ${google.length}`);
console.log(`Total after dedupe: ${all.length}`);
